config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>'homes#top'
  get "home/about"=>'homes#about'

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update] do
    get :search_post, on: :member
    resources :chats, only: [:index, :create]
    resources :relationships, only: [:create, :destroy] do
      get :follow_index, on: :collection
      get :follower_index, on: :collection
    end
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    # get :search, on: :collection (自作アクションを作成した場合にルーティング紐づけ idなし)
    # get :search, on: :member(自作アクションを作成した場合にルーティング紐づけ idあり)
    # get :search, action: :action1, on: :collection (アクションとパスが一致しない場合はactionオプションを使用)
    resources :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :searches, only: [:search] do
    get :search, on: :collection
  end
  # resources :books, only: [:index,:show,:edit,:create,:destroy,:update], concerns: [:favoritable, :book_commentable]
  # concern :favoritable do
  #   resources :favorites, only: [:create, :destroy]
  # end
  # concern :book_commentable do
  #   resources :book_comments, only: [:create, :destroy]
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#                   Prefix Verb   URI Pattern                                Controller#Action
#                     root GET    /                                          homes#top
#               home_about GET    /home/about(.:format)                      homes#about
#         new_user_session GET    /users/sign_in(.:format)                   devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                   devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                  devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)              devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)             devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                  devise/passwords#update
#                           PUT    /users/password(.:format)                  devise/passwords#update
#                           POST   /users/password(.:format)                  devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                    devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                   devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                      devise/registrations#edit
#         user_registration PATCH  /users(.:format)                           devise/registrations#update
#                           PUT    /users(.:format)                           devise/registrations#update
#                           DELETE /users(.:format)                           devise/registrations#destroy
#                           POST   /users(.:format)                           devise/registrations#create
#                     users GET    /users(.:format)                           users#index
#                 edit_user GET    /users/:id/edit(.:format)                  users#edit
#                     user GET    /users/:id(.:format)                       users#show
#                           PATCH  /users/:id(.:format)                       users#update
#                           PUT    /users/:id(.:format)                       users#update
#               search_user GET    /users/:id/search(.:format)              users#search
#           book_favorites POST   /books/:book_id/favorites(.:format)        favorites#create
#             book_favorite DELETE /books/:book_id/favorites/:id(.:format)    favorites#destroy
#                     books GET    /books(.:format)                           books#index
#                           POST   /books(.:format)                           books#create
#                 edit_book GET    /books/:id/edit(.:format)                  books#edit
#                     book GET    /books/:id(.:format)                       books#show
#                           PATCH  /books/:id(.:format)                       books#update
#                           PUT    /books/:id(.:format)                       books#update
#                           DELETE /books/:id(.:format)                       books#destroy
        # book_book_comments POST   /books/:book_id/book_comments(.:format)          book_comments#create
        # book_book_comment DELETE /books/:book_id/book_comments/:id(.:format)      book_comments#destroy
          # user_relationships POST   /users/:user_id/relationships(.:format)       relationships#create
          # user_relationship DELETE /users/:user_id/relationships/:id(.:format)   relationships#destroy
# follow_index_user_relationships GET    /users/:user_id/relationships/follow_index(.:format)    relationships#follow_index
# follower_index_user_relationships GET  /users/:user_id/relationships/follower_index(.:format)  relationships#follower_index
                        # user_chats GET    /users/:user_id/chats(.:format)         chats#index
                        #           POST   /users/:user_id/chats(.:format)         chats#create

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # フォロー機能
  has_many :relationships, foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :relationships, dependent: :destroy
  has_many :chats, foreign_key: "from_user_id"

  has_one_attached :profile_image


  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}


  # scope :today_post_books, ->{where(created_at: (1.days.ago)..(Time.now))}
  # scope :previous_post_books, ->{where(created_at: 1.day.ago.all_day)}
  # scope :thisweek_post_books, ->{where(created_at: (6.days.ago.beginning_of_day)..(Time.now))}
  # scope :lastweek_post_books, ->{where(created_at: (13.days.ago.beginning_of_day)..(1.week.ago.end_of_day))}


  #インスタンスメソッド
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def post_books_count
    #投稿数をハッシュに格納して返却するため、初期化
    post_books_cnt = {}
    # post_books_cnt = {"today_post": 0, "previous_post": 0, "thisweek_post": 0, "lastweek_post": 0}
    # post_books_cnt.clear
    #今日の投稿数(抽出条件はscopeで定義)
    post_books_cnt["today_post"] = self.books.where("created_at >= ?", Time.zone.now.beginning_of_day).count
    #前日の投稿数(抽出条件はscopeで定義)
    post_books_cnt["previous_post"] = self.books.where(created_at: 1.day.ago.all_day).count
    #今週の投稿数(抽出条件はscopeで定義)
    post_books_cnt["thisweek_post"] = self.books.where(created_at: (6.days.ago.beginning_of_day)..(Time.now)).count
    #先週の投稿数(抽出条件はscopeで定義)
    post_books_cnt["lastweek_post"] = self.books.where(created_at: (13.days.ago.beginning_of_day)..(1.week.ago.end_of_day)).count
    #前日比
    post_books_cnt["day_ratio"] = BigDecimal((post_books_cnt["previous_post"].to_f / post_books_cnt["today_post"].to_f).to_s).floor(2)*100
    #前週比
    post_books_cnt["week_ratio"] = BigDecimal((post_books_cnt["thisweek_post"].to_f / post_books_cnt["lastweek_post"].to_f).to_s).floor(2)*100

    return post_books_cnt

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Common
  before_action :set_search_window
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    #ページネーション追加#
    @books = Book.sort_books_favorite_desc(@user.id)
    # page(params[:page])
    @book = Book.new
    #投稿数関連のデータ取得#
    @post_books_cnt = User.find(params[:id]).post_books_count
    #7日間分の投稿数に関するインスタンス変数#
    @today_post_count = @user.books.today_post_books
    @previous_post_count = @user.books.previous_post_books
    @ago2_post_count = @user.books.ago2_post_books
    @ago3_post_count = @user.books.ago3_post_books
    @ago4_post_count = @user.books.ago4_post_books
    @ago5_post_count = @user.books.ago5_post_books
    @ago6_post_count = @user.books.ago6_post_books
     #投稿グラフ表示用の配列
    @graph_label = [ '6日前','5日前','4日前','3日前','2日前','1日前','今日']
    @graph_prot_count = [
        @ago6_post_count,
        @ago5_post_count,
        @ago4_post_count,
        @ago3_post_count,
        @ago2_post_count,
        @previous_post_count,
        @today_post_count
      ]
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def search_post
    user = User.find(params[:id])
    @search_post_count = user.books.date_post_books_count(params[:search_date])
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :title)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= Follower.exists?(user_id: user.id) ? Follower.find_by(user_id: user.id).users.count : 0 %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td>
          <% if user.id == current_user.id %>
            <!--何も表示しない-->
          <% elsif user.followers.exists?(user_id: current_user.id)%>
          <!--% elsif Follower.find_by(user_id: current_user.id).user.exists?(id: user.id) %>-->
            <%= link_to "フォロー外す", user_relationship_path(user.id, user.relationships.find_by(follower_id: Follower.find_by(user_id: current_user.id).id).id), method: :delete, class: "btn btn-info" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id, follower_id: current_user.id), method: :post, class: "btn btn-success" %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th>
      <%= link_to follow_index_user_relationships_path(user.id) do %>
        <%= Follower.exists?(user_id: user.id) ? Follower.find_by(user_id: user.id).users.count : 0 %>
	    <% end %>
	  </th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th>
     <%= link_to follower_index_user_relationships_path(user.id) do %>
      <%= user.followers.count %>
     <% end %>
	  </th>
  </tr>
</table>

<div class='row'>
  <% if user.id == current_user.id %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% elsif user.followers.exists?(user_id: current_user.id)%>
  <!--% elsif Follower.find_by(user_id: current_user.id).users.exists?(id: user.id) %>-->
    <%= link_to "フォロー外す", user_relationship_path(user.id, user.relationships.find_by(follower_id: Follower.find_by(user_id: current_user.id).id).id), method: :delete, class: "btn btn-info btn-block" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id, follower_id: current_user.id), method: :post, class: "btn btn-success btn-block" %>
  <% end %>
</div>
<br>
<div class='row'>
<% if user.id != current_user.id %>
  <% if user.followers.exists?(user_id: current_user.id)&&current_user.followers.exists?(user_id: user.id)%>
    <!--%= link_to "#{user.name}さんとChatする", user_relationship_chats_path(user.id, user.relationships.find_by(follower_id: Follower.find_by(user_id: current_user.id).id).id, login_user: current_user.id), method: :get, class: "btn btn-secondary btn-block" %>-->
    <%= link_to "#{user.name}さんとChatする", user_chats_path(user.id, from_user_id:current_user.id), method: :get, class: "btn btn-secondary btn-block" %>
  <% else %>
    <!--何も表示しない-->
  <% end %>
<% else %>
    <!--何も表示しない-->
<% end %>
</div>

app/views/users/_search_date_post.html.erb
<h6 class="search_window_post">投稿数の検索(日別)</h6>
<%= form_with url: search_post_user_path(user.id), method: :get, class: "form-inline ml-auto", local:false do |f| %>
  <%= f.date_field :search_date, class: "form-group form-control mr-sm-2" %>
  <%= f.submit '検索', name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>
<div id="search_result_post">
</div>

app/views/users/_search_result_post.html.erb
<h6 class="search_window_post">検索結果</h6>
<table class='table table-hover table-inverse table-bordered'>
  <thead class="table-info">
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_post_count %></td>
    </tr>
  </tbody>
</table>

app/views/users/_user_post_count.html.erb
<table class='table table-hover table-inverse table-bordered'>
  <thead class="table-info">
    <tr>
      <th>今日の投稿数</th>
      <th>前日の投稿数</th>
      <th>前日比</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= post_books_cnt["today_post"] %></td>
        <td><%= post_books_cnt["previous_post"] %></td>
        <td>
          <% if post_books_cnt["day_ratio"].nan? || post_books_cnt["day_ratio"].infinite? == 1 %>
            -
          <% else %>
            <%= post_books_cnt["day_ratio"] %>
          <% end %>
          %</td>
      </tr>
  </tbody>
</table>
<table class='table table-hover table-inverse table-bordered'>
  <thead class="table-info">
    <tr>
      <th>今週の投稿数</th>
      <th>先週の投稿数</th>
      <th>前週比</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= post_books_cnt["thisweek_post"] %></td>
        <td><%= post_books_cnt["lastweek_post"] %></td>
        <td>
        <% if post_books_cnt["week_ratio"].nan?  || post_books_cnt["week_ratio"].infinite? == 1 %>
            -
        <% else %>
          <%= post_books_cnt["week_ratio"] %>
        <% end %>
        %</td>
      </tr>
  </tbody>
</table>

app/views/users/_week_post_count.html.erb
<table class='table table-hover table-inverse table-bordered'>
  <thead class="table-info">
    <tr>
      <th>6日前</th>
      <th>5日前</th>
      <th>4日前</th>
      <th>3日前</th>
      <th>2日前</th>
      <th>1日前</th>
      <th>今日</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td>
          <%= ago6_post_count %>
        </td>
        <td>
          <%= ago5_post_count %>
        </td>
        <td>
          <%= ago4_post_count %>
        </td>
        <td>
          <%= ago3_post_count %>
        </td>
        <td>
          <%= ago2_post_count %>
        </td>
        <td>
          <%= previous_post_count %>
        </td>
        <td>
          <%= today_post_count %>
        </td>
      </tr>
  </tbody>
</table>

app/views/users/_week_post_graph.html.erb
<canvas id="myChart" width="630" height="300"></canvas>
<script>
$(document).on('turbolinks:load', function() {
  const ctx = document.getElementById('myChart').getContext('2d');
  const myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: <%= graph_label %>,
        datasets: [{
            label: '投稿した本の数',
            data: <%= graph_prot_count %>,
            backgroundColor: [
                'rgba(54, 162, 235, 0.2)'
            ],
            borderColor: [
                'rgba(54, 162, 235, 1)'
            ],
            borderWidth: 5,
            tension: 0.2
        }]
    },
    options: {
      responsive: true,
      plugins: {
        title: {
          display: true,
          text: '7日間の投稿数の比較'
        }
      },
      scales: {
        y: {
          suggestedMin: 0,
          suggestedMax: 5,
          ticks: {
            stepSize: 1
          }
        }
      },
    }
  });
});
</script>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render '/books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search_post.js.erb
$("#search_result_post").html("<%= escape_javascript(render "users/search_result_post", search_post_count: @search_post_count) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', {user: @user} %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <h2>投稿数の前日比・前週比</h2>
      <%= render 'users/user_post_count', post_books_cnt: @post_books_cnt %>
      <h2>7日間分の投稿数</h2>
      <%= render 'users/week_post_count',
      {
        today_post_count: @today_post_count,
        previous_post_count: @previous_post_count,
        ago2_post_count: @ago2_post_count,
        ago3_post_count: @ago3_post_count,
        ago4_post_count: @ago4_post_count,
        ago5_post_count: @ago5_post_count,
        ago6_post_count: @ago6_post_count
      }
      %>
      <%= render 'users/week_post_graph',
      {
        graph_label: @graph_label.to_json.html_safe,
        graph_prot_count: @graph_prot_count
      }
      %>
      <%= render 'users/search_date_post', {user: @user} %>
    </div>
  </div>
</div>