config/routes.rb
Rails.application.routes.draw do
  get 'chats/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>'homes#top'
  get "home/about"=>'homes#about'

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update] do
    get :search_post, on: :member
    resources :chats, only: [:index, :create]
    resources :relationships, only: [:create, :destroy] do
      get :follow_index, on: :collection
      get :follower_index, on: :collection
    end
  end

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    # get :search, on: :collection (自作アクションを作成した場合にルーティング紐づけ idなし)
    # get :search, on: :member(自作アクションを作成した場合にルーティング紐づけ idあり)
    # get :search, action: :action1, on: :collection (アクションとパスが一致しない場合はactionオプションを使用)
    resources :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :searches, only: [:search] do
    get :search, on: :collection
  end
  # resources :books, only: [:index,:show,:edit,:create,:destroy,:update], concerns: [:favoritable, :book_commentable]
  # concern :favoritable do
  #   resources :favorites, only: [:create, :destroy]
  # end
  # concern :book_commentable do
  #   resources :book_comments, only: [:create, :destroy]
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#                   Prefix Verb   URI Pattern                                Controller#Action
#                     root GET    /                                          homes#top
#               home_about GET    /home/about(.:format)                      homes#about
#         new_user_session GET    /users/sign_in(.:format)                   devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                   devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                  devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)              devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)             devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                  devise/passwords#update
#                           PUT    /users/password(.:format)                  devise/passwords#update
#                           POST   /users/password(.:format)                  devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                    devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                   devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                      devise/registrations#edit
#         user_registration PATCH  /users(.:format)                           devise/registrations#update
#                           PUT    /users(.:format)                           devise/registrations#update
#                           DELETE /users(.:format)                           devise/registrations#destroy
#                           POST   /users(.:format)                           devise/registrations#create
#                     users GET    /users(.:format)                           users#index
#                 edit_user GET    /users/:id/edit(.:format)                  users#edit
#                     user GET    /users/:id(.:format)                       users#show
#                           PATCH  /users/:id(.:format)                       users#update
#                           PUT    /users/:id(.:format)                       users#update
#               search_user GET    /users/:id/search(.:format)              users#search
#           book_favorites POST   /books/:book_id/favorites(.:format)        favorites#create
#             book_favorite DELETE /books/:book_id/favorites/:id(.:format)    favorites#destroy
#                     books GET    /books(.:format)                           books#index
#                           POST   /books(.:format)                           books#create
#                 edit_book GET    /books/:id/edit(.:format)                  books#edit
#                     book GET    /books/:id(.:format)                       books#show
#                           PATCH  /books/:id(.:format)                       books#update
#                           PUT    /books/:id(.:format)                       books#update
#                           DELETE /books/:id(.:format)                       books#destroy
        # book_book_comments POST   /books/:book_id/book_comments(.:format)          book_comments#create
        # book_book_comment DELETE /books/:book_id/book_comments/:id(.:format)      book_comments#destroy
          # user_relationships POST   /users/:user_id/relationships(.:format)       relationships#create
          # user_relationship DELETE /users/:user_id/relationships/:id(.:format)   relationships#destroy
# follow_index_user_relationships GET    /users/:user_id/relationships/follow_index(.:format)    relationships#follow_index
# follower_index_user_relationships GET  /users/:user_id/relationships/follower_index(.:format)  relationships#follower_index
                        # user_chats GET    /users/:user_id/chats(.:format)         chats#index
                        #           POST   /users/:user_id/chats(.:format)         chats#create

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence:true
  validates :body, presence:true,length:{maximum:200}

  scope :today_post_books, ->{where("created_at >= ?", Time.zone.now.beginning_of_day).count}
  scope :previous_post_books, ->{where(created_at: 1.day.ago.all_day).count}
  scope :ago2_post_books, ->{where(created_at: 2.day.ago.all_day).count}
  scope :ago3_post_books, ->{where(created_at: 3.day.ago.all_day).count}
  scope :ago4_post_books, ->{where(created_at: 4.day.ago.all_day).count}
  scope :ago5_post_books, ->{where(created_at: 5.day.ago.all_day).count}
  scope :ago6_post_books, ->{where(created_at: 6.day.ago.all_day).count}

  # scope :books_favorite_sort, ->{left_joins(:favorites).select('books.*, count(favorites.book_id) as fav_count').group(:book_id).order(Arel.sql('fav_count desc'))}
  #クラスメソッド#

  def self.date_post_books_count(search_date)
    count_result =  Book.where(created_at: search_date.in_time_zone.all_day).count
    return count_result
  end

  # def self.sort_books_favorite_desc
  #   result = ActiveRecord::Base.connection.select_all('select b.*, f.cnt from books b left outer join (select book_id, count(book_id) as cnt from favorites group by book_id) f on b.id = f.book_id order by f.cnt desc')
  #   return result.to_a
  # end


  # def self.sort_books_favorite_desc_user(user_id)
  #   result = ActiveRecord::Base.connection.select_all('select b.*, f.cnt from books b left outer join (select book_id, count(book_id) as cnt from favorites group by book_id) f on b.id = f.book_id where b.user_id = #{user_id} order by f.cnt desc')
  #   return result.to_a
  # end

  def self.sort_books_favorite_desc(*args)
    if args.length == 0
      result = ActiveRecord::Base.connection.select_all('select b.*, f.cnt from books b left outer join (select book_id, count(book_id) as cnt from favorites group by book_id) f on b.id = f.book_id order by f.cnt desc')
    elsif args.length == 1
      #プレースホルダー
      sql = ActiveRecord::Base.sanitize_sql_array(['select b.*, f.cnt from books b left outer join (select book_id, count(book_id) as cnt from favorites group by book_id) f on b.id = f.book_id where b.user_id = (:user_id) order by f.cnt desc', user_id: args[0]])
      #生SQL実行
      result = ActiveRecord::Base.connection.select_all(sql)
      # result = ActiveRecord::Base.connection.select_all('select b.*, f.cnt from books b left outer join (select book_id, count(book_id) as cnt from favorites group by book_id) f on b.id = f.book_id where b.user_id = "#{args[0]}" order by f.cnt desc')
      # binding.pry
    else
      result = 0
    end
    return result.to_a
  end

  #インスタンスメソッド#

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Common
  before_action :set_search_window
  before_action :verifi_datauser_loginuser_mdlbook, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_r = Book.new
    # @book_comments = Book.book_comments
    @book_comment = BookComment.new
  end

  def search
  end

  def index
    #ページネーション追加
    # @books = Book.all.page(params[:page])
    # @books = Book.books_favorite_sort.page(params[:page])
    @books = Book.sort_books_favorite_desc
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all.page(params[:page])
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def verifi_datauser_loginuser_mdlbook
    unless current_user.id.to_s == Book.find_by(id: params[:id]).user_id.to_s
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<%= form_with model: book_comment, url: book_book_comments_path(book.id), id: "comment_form", local:false do |f| %>
  <div class="form-group">
    <%= f.text_area :comment, autofocus: true, class: 'form-control book_body', rows: '5' %>
  </div>
  <div class="form-group">
    <%= f.submit "送信", class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/books/_comment_index.html.erb
<table id="comment_index">
<% book.book_comments.each do |bc| %>
<tr>
  <td>
    <%= link_to user_path(bc.user_id) do %>
    <%= image_tag bc.user.get_profile_image, size:"120x120" %><br>
    <%= bc.user.name %>
    <% end %>
  </td>
  <td>
    <%= bc.comment %>
  </td>
  <td>
    <% if bc.user_id == current_user.id %>
      <%= link_to 'Destroy', book_book_comment_path(bc.book_id, bc.id), method: :delete, class: "btn btn-sm btn-danger", remote:true %>
    <% end %>
  </td>
</tr>
<% end %>
</table>

app/views/books/_favorite.html.erb
<% if Book.find(book["id"]).favorites.exists?(user_id: current_user.id) %>
  <%= link_to book_favorite_path(book["id"], Book.find(book["id"]).favorites.find_by(user_id: current_user.id).id, disp_id: "v_index"),
  method: :delete, class: "fav_icon_destroy",id: "fav_#{book["id"]}", remote: true do %>
    <span class="fas fa-heart"></span>
    <%= Book.find(book["id"]).favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book["id"], disp_id: "v_index"),
  method: :post, class: "fav_icon_create",id: "fav_#{book["id"]}", remote: true do %>
    <span class="fas fa-heart"></span>
    <%= Book.find(book["id"]).favorites.count %>
  <% end %>
<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse', id='books_index'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to(user_path(book["user_id"])) do %>
            <%= image_tag Book.find(book["id"]).user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book["title"],book_path(book["id"]), class: "book_#{book["id"]}" %></td>
        <td><%= book["body"] %></td>
        <td>
          <%= render "books/favorite", {book: book} %>
        </td>
        <td>
          コメント数:<%= Book.find(book["id"]).book_comments.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--%= paginate books %>-->

app/views/books/edit.html.erb
<div class='container'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', {user: @user}  %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_r %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <%= render "favorite", {book: @book} %>
          </td>
          <td>
            コメント数:<%= @book.book_comments.count %>
          </td>
          <% if @book.user.id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <%= render "books/comment_index", {book: @book} %>
      <%= render "books/comment", {book_comment: @book_comment, book: @book} %>
  </div>
</div>